name: Run Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: pip install 
        run: pip install -e .[test]
      
      - name: Run tests
        run : pytest
