# Package ######################################################################

[build-system]
requires = ["setuptools >= 61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "posggym"
description = "A library for planning and reinforcement learning research in partially observable, multi-agent environments."
readme = "README.md"
requires-python = ">= 3.10"
authors = [
	{ name = "Jonathon Schwartz", email = "jonathon.schwartz@anu.edu.au" },
]
license = { text = "MIT License" }
keywords = [
	"multiagent-systems",
	"reinforcement-learning",
	"planning",
	"gymnasium",
	"POSG",
]
classifiers = [
	# change to `5 - Production/Stable` maybe one day
	"Development Status :: 4 - Beta",
	"License :: OSI Approved :: MIT License",
	"Programming Language :: Python :: 3",
	"Programming Language :: Python :: 3.8",
	"Programming Language :: Python :: 3.9",
	"Programming Language :: Python :: 3.10",
	"Programming Language :: Python :: 3.11",
	'Intended Audience :: Science/Research',
	'Topic :: Scientific/Engineering :: Artificial Intelligence',
]
dependencies = [
    "gymnasium>=0.26,<=0.29.1",
	"numpy >=1.21.0",
	"typing-extensions >=4.3.0",
	"importlib-metadata >=4.8.0; python_version < '3.10'",
	"pygame >=2.0",
	"pymunk >=6.0.0, <7.0.0",
	"vmas==1.4.1"
]
dynamic = ["version"]

[project.optional-dependencies]
# Update dependencies in `all` if any are added or removed
agents = [
	"types-requests >=2.28",
	"requests >= 2.28",
	"clint >= 0.5.1",
	"torch >=1.11.0",
]
other = [
	# Dependencies used in wrappers, notebooks, and scripts
	"moviepy >=1.0.0",
	"pandas >=1.0",
	"seaborn >=0.13.0",
	"matplotlib >=3.0.0",
]
all = [
	# Dependencieis for all envs and agents
	# agents
	"types-requests >=2.28",
	"requests >= 2.28",
	"clint >= 0.5.1",
	"torch >= 2.0",
	# other
	"moviepy >=1.0.0",
	"seaborn >=0.11.1",
	"matplotlib >=3.3.4",
	"pandas >=1.0",
]
testing = ["pytest >=7.2"]

[project.urls]
Homepage = "https://github.com/RDLLab/posggym"
Repository = "https://github.com/RDLLab/posggym/"
Documentation = "https://posggym.readthedocs.io/"
"Bug Report" = "https://github.com/RDLLab/posggym/issues"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["posggym", "posggym.*"]

[tool.setuptools.package-data]
posggym = ["envs/grid_world/img/*.png", "py.typed"]

# Linters and Test tools #######################################################
[tool.ruff]
src = ["posggym", "tests", "docs/scripts", "scripts", "examples", "notebooks"]
show-fixes = true
# Same as Black.
line-length = 88
# Assume Python 3.10.
target-version = "py310"

[tool.ruff.lint]
extend-select = ["C4", "SIM", "TCH"]

ignore = [
    "A001", "A002",
    "ARG001", "ARG002",
    "FBT001", "FBT002", "FBT003",
    "N802", "N806", "N812",
    "PGH003", "PGH004",
    "S101", "S202", "S301", "S310", "S311",
	"T201", "T203"
]

select = [
    "A",
    "ARG",
    "B",
    "C4",
    "C90",
    "E",
    "ERA",
    "F",
    "FBT",
    "ICN",
    "I",
    "ISC",
    "N",
    "NPY",
    "PD",
    "PGH",
    "PIE",
    "PLE",
    "PLR",
    "Q",
    "RUF",
    "S",
    "SIM",
    "T",
    "UP",
    "W",
]
# Ignore `F401` (import violations) in all `__init__.py` files,
[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401", "E402"]
"tests/**/*.py" = ["PLR2004", "N802", "N801"]
"docs/conf.py" = ["A001"]
"docs/**/*.py" = ["PLR2004"]
"posggym/utils/**.py" = ["PLR2004"]

[tool.ruff.lint.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 30

[tool.ruff.lint.isort]
lines-after-imports = 2
extra-standard-library = ["typing_extensions"]

[tool.ruff.lint.pylint]
max-statements = 100
max-branches=20
max-args=15


[tool.black]
line-length = 88

[tool.pyright]
include = ["posggym/**"]
exclude = ["**/node_modules", "**/__pycache__"]
strict = []

typeCheckingMode = "basic"
pythonVersion = "3.10"
pythonPlatform = "All"
enableTypeIgnoreComments = true

# This is required as the CI pre-commit does not download the module (i.e. numpy, pygame, box2d)
#   Therefore, we have to ignore missing imports
reportMissingImports = "none"
# Some modules are missing type stubs, which is an issue when running pyright locally
reportMissingTypeStubs = false
# For warning and error, will raise an error when
reportInvalidTypeVarUse = "none"

reportGeneralTypeIssues = "none" # -> commented out raises 489 errors
# reportUntypedFunctionDecorator = "none"  # -> pytest.mark.parameterize issues

reportPrivateUsage = "warning"
reportUnboundVariable = "warning"
reportOptionalOperand = "warning"

[tool.pytest.ini_options]
filterwarnings = [
	# Tensorboard warnings
	"ignore::DeprecationWarning:tensorboard",
	# Gymnasium warnings
	"ignore::UserWarning:gymnasium",
	# PettingZoo warnings
	"ignore::UserWarning:pettingzoo",
]
